Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 1024
    end

    config.vm.define "aschiffeS" do |control|
        control.vm.hostname = "aschiffeS"
        control.vm.network "private_network", ip: "192.168.56.110", type: "dhcp"
    end

    config.vm.define "aschiffeSW" do |control|
        control.vm.hostname = "aschiffeSW"
        control.vm.network "private_network", ip: "192.168.56.111", type: "dhcp"
    end
end