Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 1024
    end

    config.vbguest.installer_options = { allow_kernel_upgrade: true }

    config.vm.define "aschiffeS" do |control|
        control.vm.hostname = "aschiffeS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provision "shell", path: "provisions/s_provisioner.sh"
        control.vm.synced_folder "./provisions/shared", "/home/vagrant/shared", type: "virtualbox"
    end

    config.vm.define "aschiffeSW" do |control|
        control.vm.hostname = "aschiffeSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provision "shell", path: "provisions/sw_provisioner.sh"
        control.vm.synced_folder "./provisions/shared", "/home/vagrant/shared", type: "virtualbox"
    end
end
